name: C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
      
    - name: Set up CMake
      run: |
        sudo apt-get update
        sudo apt-get -y install cmake

    - name: Create Build Directory
      run: mkdir build

    - name: Build Project
      run: |
        cd build
        cmake ..
        make

    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure

